export const AD_SCENES = [
  {
    eyebrow: "VENNET PRESENTS",
    title: "Build your own lane.",
    body: "Your skills deserve more than a hidden folder.",
    button: "MAKE IT YOURS",
    caption: "CLIP 01 · THE SWITCH-UP",
    vibe: "signal",
  },
  {
    eyebrow: "SELL ON VENNET",
    title: "Let your work work.",
    body: "Bots, automations, designs, tools. Put them where buyers can find them.",
    button: "START SELLING",
    caption: "CLIP 02 · WHILE YOU SLEEP",
    vibe: "bot",
  },
  {
    eyebrow: "CREATOR ENERGY",
    title: "Idea. Drop. Repeat.",
    body: "Turn the thing you make into a storefront people remember.",
    button: "DROP YOUR OFFER",
    caption: "CLIP 03 · MAKE THE DROP",
    vibe: "drop",
  },
  {
    eyebrow: "BUY FROM CREATORS",
    title: "Find your next advantage.",
    body: "Real digital tools from independent creators—ready when you are.",
    button: "EXPLORE VENNET",
    caption: "CLIP 04 · FIND THE EDGE",
    vibe: "find",
  },
  {
    eyebrow: "FIVEM · SCRIPTS · MLOs",
    title: "Ship the script. Skip the DMs.",
    body: "Sell your FiveM resources with instant delivery, real receipts and zero chargeback drama.",
    button: "LIST YOUR SCRIPT",
    caption: "CLIP 05 · FOR FIVEM DEVS",
    vibe: "fivem",
  },
  {
    eyebrow: "DISCORD BOT BUILDERS",
    title: "Your bot. Paid on repeat.",
    body: "Package the bot once. Every buyer gets the files and setup guide the second they pay.",
    button: "SELL YOUR BOT",
    caption: "CLIP 06 · BOT MONEY",
    vibe: "discord",
  },
  {
    eyebrow: "GET PAID PROPERLY",
    title: "Stripe in. Money out.",
    body: "Secure checkout, automatic payouts, order history you can actually show people.",
    button: "CONNECT STRIPE",
    caption: "CLIP 07 · THE PAYOUT",
    vibe: "payout",
  },
  {
    eyebrow: "HOW IT WORKS",
    title: "Three steps. One storefront.",
    body: "Join free. Upload your offer. Share your link. That's the whole tutorial.",
    button: "START IN 60 SECONDS",
    caption: "CLIP 08 · THE TUTORIAL",
    vibe: "steps",
  },
  {
    eyebrow: "STOP SELLING IN DMS",
    title: "\"Paid?\" \"Send file?\" Never again.",
    body: "Vennet handles payment, delivery and proof. You just make the thing.",
    button: "MOVE TO VENNET",
    caption: "CLIP 09 · THE UPGRADE",
    vibe: "dm",
  },
  {
    eyebrow: "BUYERS · TRUST BUILT IN",
    title: "Buy from real creators.",
    body: "Verified sellers, clear delivery, every purchase saved in your library.",
    button: "BROWSE THE MARKETPLACE",
    caption: "CLIP 10 · FOR BUYERS",
    vibe: "trust",
  },
  {
    eyebrow: "NO FEES TO START",
    title: "Free to open. Free to list.",
    body: "Zero monthly cost. Upgrade to Pro only when your storefront needs more reach.",
    button: "OPEN YOUR STOREFRONT",
    caption: "CLIP 11 · THE OFFER",
    vibe: "free",
  },
  {
    eyebrow: "JOIN FREE TODAY",
    title: "Your work. Your storefront.",
    body: "Sign up in seconds. List in minutes. Get paid through Stripe.",
    button: "VENNETOFFICIAL.VERCEL.APP",
    caption: "CLIP 12 · THE CLOSE",
    vibe: "outro",
  },
] as const;

export type AdSceneData = (typeof AD_SCENES)[number];
