import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Legal Notices | Vennet", description: "Legal notices and important information for Vennet users." };

const notices: Array<[string, string[]]> = [
  ["Effective legal notices", ["These are Vennet’s published Legal Notices, effective August 26, 2026. Vennet is a Michigan sole proprietorship operated by its responsible adult owner. They supplement and are incorporated into Vennet’s Terms of Service and Privacy Policy. By using Vennet, you acknowledge these Legal Notices.", "Vennet may revise these Legal Notices by posting an updated version with a revised effective date."]],
  ["Marketplace status", ["Vennet is a digital-only marketplace platform. Unless Vennet expressly says otherwise in writing, Sellers—not Vennet—are responsible for their individual listings, descriptions, licenses, deliverables, support, tax obligations, and Buyer-Seller transactions.", "Vennet may provide tools for listings, communication, delivery, payments, seller verification, and dispute handling. Providing those tools does not make Vennet the seller of a third-party Offer or a party to the Buyer-Seller contract."]],
  ["Payments and Stripe", ["Vennet uses Stripe and Stripe Connect to process payments and route eligible seller proceeds. Payment processing, connected accounts, payout timing, reserves, reversals, and related services are subject to Stripe’s terms, policies, and operational decisions.", "Vennet retains its disclosed platform fee from completed marketplace transactions. Sellers are responsible for their own taxes, refunds, chargebacks, negative balances, and obligations connected to their Offers, subject to applicable law and the Vennet Terms of Service."]],
  ["Intellectual property and copyright", ["The Vennet name, logo, website design, software, and Vennet-created content are protected by applicable intellectual-property laws. You may not use Vennet branding or content in a way that suggests endorsement, affiliation, or sponsorship without written permission.", "For copyright notices or counter-notices under the Digital Millennium Copyright Act, contact: DMCA Agent, Vennet Legal, vennetofficial@gmail.com. Include the information required by applicable law so we can evaluate the request."]],
  ["No professional advice", ["Content on Vennet, including Vennet AI output, marketplace listings, Help materials, and communications, is for general information and marketplace use. It is not legal, tax, financial, investment, medical, security, or other professional advice.", "You are responsible for reviewing information and obtaining qualified professional advice where appropriate. Do not rely on AI output or marketplace content as the sole basis for an important decision."]],
  ["Third-party services and links", ["Vennet may link to or rely on third-party services, including Stripe, Google, email providers, identity-verification providers, hosting providers, and AI providers. Those services are governed by their own terms and privacy policies. Vennet does not control and is not responsible for third-party content, availability, security, or practices except where required by law."]],
  ["Policy documents", ["Your use of Vennet is governed by the Terms of Service and Privacy Policy. These notices supplement those documents but do not replace them. If there is a conflict, the Terms of Service control to the extent permitted by law.", "Vennet may revise its policies and notices as the Services or legal requirements change. Revised documents are effective when posted or as otherwise stated in the revised document."]],
  ["Contact", ["For general legal or policy questions, email vennetofficial@gmail.com. For payment-processor questions, contact Stripe through the Stripe Dashboard or Stripe Support."]],
];

export default function LegalPage() {
  return <article className="mx-auto max-w-4xl space-y-6"><header className="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-950/15 sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Vennet legal</p><h1 className="mt-3 text-4xl font-black tracking-tight">Legal Notices</h1><p className="mt-3 text-sm font-medium text-slate-300">Effective August 26, 2026 · Last updated August 26, 2026</p><p className="mt-5 max-w-3xl leading-7 text-slate-200">These are Vennet’s current, effective legal notices for the marketplace, third-party services, and user responsibilities.</p></header>{notices.map(([heading, paragraphs]) => <section key={heading} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/[0.04]"><h2 className="text-xl font-black text-slate-950">{heading}</h2><div className="mt-4 space-y-4 leading-7 text-slate-700">{paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>)}<p className="pb-4 text-center text-sm font-semibold text-slate-600"><Link href="/terms" className="text-emerald-800 hover:underline">Terms of Service</Link><span className="mx-2">·</span><Link href="/privacy" className="text-emerald-800 hover:underline">Privacy Policy</Link></p></article>;
}
