import Link from "next/link";
import { BrandMark } from "@/components/BrandMark";

const categories = [
  { icon: "✦", title: "Digital products", body: "Templates, downloads, tools, and creative assets ready instantly.", href: "/marketplace?category=digital", color: "from-emerald-400 to-teal-400" },
  { icon: "◌", title: "Creative services", body: "Sell expert work with clear scopes, delivery, and support.", href: "/marketplace?category=services", color: "from-cyan-400 to-blue-400" },
  { icon: "↗", title: "Memberships", body: "Build recurring access around the work your audience values.", href: "/dashboard/seller", color: "from-lime-400 to-emerald-400" },
];

export default function HomePage() {
  return <div className="overflow-hidden pb-5">
    <section className="relative grid gap-10 py-10 lg:grid-cols-[1.08fr_0.92fr] lg:items-center lg:py-20">
      <div className="pro-glow pro-glow-left animate-drift" />
      <div className="relative">
        <div className="animate-rise inline-flex items-center gap-2 rounded-full border border-emerald-700/20 bg-white/70 px-3 py-1.5 text-xs font-bold text-emerald-900 shadow-sm"><span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />The marketplace for digital creators</div>
        <h1 className="animate-rise-delay mt-6 max-w-3xl text-5xl font-black leading-[0.92] tracking-[-0.065em] text-slate-950 sm:text-7xl">Turn creative work into <span className="bg-gradient-to-r from-emerald-700 via-teal-600 to-cyan-700 bg-clip-text text-transparent">real momentum.</span></h1>
        <p className="animate-rise-delay-2 mt-7 max-w-xl text-lg leading-8 text-slate-700">Vennet gives creators one beautiful place to sell digital products, services, and memberships—without the clutter of a traditional store.</p>
        <div className="animate-rise-delay-2 mt-8 flex flex-wrap gap-3"><Link href="/marketplace" className="button-primary">Explore the marketplace <span className="ml-2">→</span></Link><Link href="/dashboard/seller" className="inline-flex items-center justify-center rounded-xl border border-slate-300 bg-white px-5 py-3 font-bold text-slate-800 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300">Start selling</Link></div>
        <div className="animate-rise-delay-2 mt-10 grid max-w-xl grid-cols-3 gap-3 border-t border-slate-300/70 pt-5"><div><p className="text-2xl font-black text-slate-950">5%</p><p className="mt-1 text-xs font-semibold text-slate-600">simple platform fee</p></div><div><p className="text-2xl font-black text-slate-950">24/7</p><p className="mt-1 text-xs font-semibold text-slate-600">digital delivery</p></div><div><p className="text-2xl font-black text-slate-950">Stripe</p><p className="mt-1 text-xs font-semibold text-slate-600">secure payments</p></div></div>
      </div>
      <div className="animate-rise-delay relative mx-auto w-full max-w-lg">
        <div className="absolute -inset-8 -z-10 rounded-full bg-emerald-400/20 blur-3xl animate-pulse-glow" />
        <div className="overflow-hidden rounded-[2rem] border border-slate-800 bg-slate-950 p-5 shadow-2xl shadow-slate-950/30 sm:p-7">
          <div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-emerald-300 to-teal-400"><BrandMark className="h-8 w-8" /></span><div><p className="font-black text-white">Creator studio</p><p className="text-xs text-slate-400">Your work, in motion</p></div></div><span className="rounded-full bg-emerald-400/15 px-2.5 py-1 text-xs font-bold text-emerald-300">Live</span></div>
          <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.04] p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">This month</p><div className="mt-2 flex items-end justify-between"><p className="text-4xl font-black tracking-tight text-white">$2,480<span className="text-base text-slate-400">.00</span></p><span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs font-bold text-emerald-300">↗ 18.7%</span></div><div className="mt-5 flex h-16 items-end gap-1.5">{[28, 42, 34, 53, 47, 68, 62, 79, 73, 91].map((height, index) => <span key={index} style={{ height: height + "%" }} className="flex-1 rounded-t bg-gradient-to-t from-emerald-500 to-teal-300 opacity-80 transition duration-500 hover:opacity-100" />)}</div></div>
          <div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold text-slate-400">Digital orders</p><p className="mt-1 text-2xl font-black text-white">128</p></div><div className="rounded-xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold text-slate-400">Buyer rating</p><p className="mt-1 text-2xl font-black text-white">4.9 <span className="text-sm text-emerald-300">★</span></p></div></div>
        </div>
      </div>
    </section>

    <section className="relative mt-4 rounded-[2rem] border border-slate-200 bg-white/70 p-6 shadow-[0_20px_50px_rgb(15_23_42/0.08)] backdrop-blur sm:p-8">
      <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold text-emerald-800">Built for every kind of digital craft</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Find your next best-seller.</h2></div><Link href="/marketplace" className="font-bold text-emerald-800 hover:text-emerald-950">Browse all offers →</Link></div>
      <div className="mt-7 grid gap-4 md:grid-cols-3">{categories.map((category, index) => <Link key={category.title} href={category.href} className="group relative overflow-hidden rounded-2xl bg-slate-950 p-6 transition duration-300 hover:-translate-y-1 hover:shadow-xl" style={{ animationDelay: index * 90 + "ms" }}><div className={"absolute right-0 top-0 h-28 w-28 rounded-full bg-gradient-to-br opacity-20 blur-2xl " + category.color} /><span className={"grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br text-lg font-black text-slate-950 " + category.color}>{category.icon}</span><h3 className="mt-6 text-xl font-black text-white">{category.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{category.body}</p><span className="mt-5 inline-block text-sm font-bold text-emerald-300">Explore <span className="transition group-hover:ml-1">→</span></span></Link>)}</div>
    </section>

    <section className="mt-6 grid gap-4 lg:grid-cols-[1fr_1.35fr]"><div className="rounded-3xl bg-emerald-900 p-7 text-white shadow-xl shadow-emerald-950/20"><p className="text-sm font-bold text-emerald-200">Built-in trust</p><h2 className="mt-3 text-3xl font-black leading-tight">Sell with confidence. Buy with clarity.</h2><p className="mt-4 leading-7 text-emerald-50/85">Verified seller status, clear delivery details, protected Stripe checkout, and direct support after every purchase.</p><Link href="/terms" className="mt-6 inline-block text-sm font-bold text-white underline decoration-emerald-300 underline-offset-4">How Vennet protects you</Link></div><div className="console-panel grid gap-5 p-7 sm:grid-cols-3"><div><p className="text-2xl font-black text-emerald-300">One link</p><p className="mt-2 text-sm leading-6 text-slate-400">Share a listing anywhere and deliver right after payment.</p></div><div className="border-l-0 border-white/10 pl-0 sm:border-l sm:pl-5"><p className="text-2xl font-black text-white">No shipping</p><p className="mt-2 text-sm leading-6 text-slate-400">Designed entirely around digital products and online work.</p></div><div className="border-l-0 border-white/10 pl-0 sm:border-l sm:pl-5"><p className="text-2xl font-black text-white">Made to grow</p><p className="mt-2 text-sm leading-6 text-slate-400">Upgrade to Pro when your catalog and audience expand.</p></div></div></section>
  </div>;
}