"use client";

import { useState } from "react";

const guides = [
  { number: "01", title: "Buy a digital item", summary: "Find an offer, review what you receive, and pay through Stripe.", steps: ["Open Explore and choose a category or use marketplace filters.", "Read the delivery, license, compatibility, and support details.", "Use Buy now or add compatible offers to your cart.", "After payment, open My library for files, access instructions, and seller support."] },
  { number: "02", title: "Set up your seller account", summary: "Connect Stripe before creating your first digital offer.", steps: ["Open Seller tools in the header.", "Choose Payout setup and complete Stripe onboarding.", "Return to Seller tools and select Create a listing.", "Add complete delivery and support information before publishing."] },
  { number: "03", title: "Create a great listing", summary: "Help buyers understand exactly what they are getting.", steps: ["Add a clear title, description, category, and price.", "Upload the digital file or provide accurate access instructions.", "Include license terms, compatibility, update policy, and support expectations.", "Add a preview image or demo, then publish when ready."] },
  { number: "04", title: "Find a past purchase", summary: "Everything you own lives in one organized library.", steps: ["Choose My library from the top navigation.", "Open the purchase you need.", "Download the file or follow the access instructions.", "Use the purchase support area if you need help from the seller."] },
];

export function HelpGuides() {
  const [selected, setSelected] = useState<(typeof guides)[number] | null>(null);
  return <section><div className="mb-5"><p className="text-sm font-black uppercase tracking-[.16em] text-emerald-700">Tutorials</p><h2 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Start here</h2><p className="mt-2 text-sm text-slate-600">Choose a guide to keep its instructions open at the side of the page.</p></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_22rem]">
      <div className="grid gap-5 md:grid-cols-2">{guides.map((guide) => <button key={guide.number} type="button" onClick={() => setSelected(guide)} className={"rounded-3xl border p-6 text-left shadow-lg shadow-slate-900/[0.04] transition hover:-translate-y-0.5 hover:shadow-xl " + (selected?.number === guide.number ? "border-emerald-400 bg-emerald-50" : "border-slate-200 bg-white")}><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-100 text-sm font-black text-emerald-800">{guide.number}</span><div><h3 className="text-xl font-black text-slate-950">{guide.title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{guide.summary}</p></div></div><span className="mt-5 inline-block text-sm font-black text-emerald-800">Open guide →</span></button>)}</div>
      <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/[0.06] xl:sticky xl:top-28">{selected ? <><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Guide {selected.number}</p><h3 className="mt-2 text-2xl font-black text-slate-950">{selected.title}</h3></div><button type="button" onClick={() => setSelected(null)} className="rounded-lg border border-slate-200 px-2 py-1 text-sm font-black text-slate-500 hover:bg-slate-50">×</button></div><p className="mt-3 text-sm leading-6 text-slate-600">{selected.summary}</p><ol className="mt-6 space-y-4">{selected.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-slate-700"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-emerald-100 text-xs font-black text-emerald-800">{index + 1}</span><span>{step}</span></li>)}</ol></> : <div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Guide panel</p><h3 className="mt-2 text-xl font-black">Keep steps in view.</h3><p className="mt-2 text-sm leading-6 text-slate-300">Select a tutorial and its instructions will stay here while you work through Vennet.</p></div>}</aside>
    </div>
  </section>;
}
