import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy | Vennet", description: "How Vennet collects, uses, and protects personal information." };

const sections: Array<[string, string[]]> = [
  ["1. Scope", ["This Privacy Policy explains how Vennet collects, uses, retains, and shares information when you use the Vennet website, marketplace, creator tools, payment features, support tools, and related services. It applies alongside our Terms of Service and any additional notice provided at the time information is collected.", "Vennet is a Michigan-based digital-only marketplace. Questions about this Policy may be sent to vennetofficial@gmail.com."]],
  ["2. Information we collect", ["We collect information you provide directly, such as your email address, password (stored in protected form), display name, profile information, listing content, support messages, identity-verification information, and communications with Vennet.", "We collect transaction and marketplace information, including purchases, listings, delivery information, Stripe account status, payout and dispute records, product access records, and related activity. We also collect technical information necessary to operate and protect the Services, such as cookie preferences, session identifiers, browser and device information, IP-related security information, and usage activity."]],
  ["3. How we use information", ["We use information to create and secure Accounts; provide marketplace, delivery, support, payment, payout, verification, and AI features; personalize saved settings; prevent fraud and abuse; enforce our policies; communicate with you; resolve disputes; comply with law; and improve the Services.", "We may use aggregated or de-identified information for analytics, operations, security, and product improvement. We do not use full payment-card numbers to operate Vennet because payment-card entry and processing are handled by Stripe."]],
  ["4. Payments, Stripe, and connected accounts", ["Payments and seller payouts are processed by Stripe and Stripe Connect. Stripe receives and processes payment and payout information under its own terms and privacy policy. Vennet may receive transaction, payout, verification, fraud, and status information from Stripe that is needed to operate the marketplace, administer fees, deliver orders, respond to disputes, and comply with legal obligations.", "Vennet does not intentionally store full payment-card numbers on its servers. Stripe uses its own payment infrastructure, security controls, and tokenization tools."]],
  ["5. Cookies and sessions", ["Vennet uses essential cookies and similar browser storage to keep you signed in, protect Accounts, remember settings, support security controls, and operate the website. Our sign-in session is designed to persist for up to 30 days unless you sign out, clear browser data, or your session is otherwise ended for security reasons.", "You can control many browser cookies through browser settings. Disabling essential cookies may prevent sign-in, saved settings, or other core features from working correctly."]],
  ["6. When we share information", ["We share information with service providers that help us run Vennet, including Stripe for payments and payouts, hosting and infrastructure providers, email delivery providers, identity-verification providers, and AI providers when you choose to use the related feature. We share only what is reasonably necessary for the service or as otherwise permitted by law.", "We may also disclose information to comply with law, enforce our agreements, protect Vennet and its users, investigate fraud or security incidents, respond to valid legal process, or support a merger, financing, acquisition, sale of assets, or similar business transaction."]],
  ["7. Retention and security", ["We retain information for as long as reasonably necessary to provide the Services, meet legal and tax obligations, prevent fraud, resolve disputes, enforce our agreements, and maintain appropriate business records. After Account deletion, we may retain transaction, payout, verification, dispute, support, security, and fraud records where reasonably necessary for those purposes.", "We use reasonable administrative, technical, and organizational safeguards designed to protect information. No service or transmission is completely secure, so we cannot guarantee absolute security."]],
  ["8. Your choices and requests", ["You can update many profile and preference details through your Account. You may ask about access, correction, deletion, or other privacy requests by emailing vennetofficial@gmail.com. We may need to verify your identity and may retain information where law, security, fraud prevention, disputes, payments, or other legitimate requirements allow or require retention.", "Vennet is not directed to children under 13. If you believe a child under 13 provided personal information without required permission, contact us so we can review the request."]],
  ["9. Changes and contact", ["We may update this Policy as our practices or legal obligations change. We will post the revised Policy and update its effective date. Continued use after a revision takes effect is subject to the updated Policy to the extent permitted by law.", "Effective date: August 25, 2026. Contact Vennet privacy support at vennetofficial@gmail.com. See also our Terms of Service and Legal Notices."]],
];

export default function PrivacyPage() {
  return <article className="mx-auto max-w-4xl space-y-6"><header className="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-950/15 sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Vennet legal</p><h1 className="mt-3 text-4xl font-black tracking-tight">Privacy Policy</h1><p className="mt-3 text-sm font-medium text-slate-300">Effective August 25, 2026 · Last updated August 25, 2026</p><p className="mt-5 max-w-3xl leading-7 text-slate-200">This Policy describes how Vennet handles personal information in clear, practical terms.</p></header>{sections.map(([heading, paragraphs]) => <section key={heading} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/[0.04]"><h2 className="text-xl font-black text-slate-950">{heading}</h2><div className="mt-4 space-y-4 leading-7 text-slate-700">{paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>)}<p className="pb-4 text-center text-sm font-semibold text-slate-600"><Link href="/terms" className="text-emerald-800 hover:underline">Terms of Service</Link><span className="mx-2">·</span><Link href="/legal" className="text-emerald-800 hover:underline">Legal Notices</Link></p></article>;
}
