import Link from "next/link";
import { IdentityForm } from "@/components/forms/IdentityForm";
import { RecentlyViewedShelf } from "@/components/RecentlyViewedShelf";
import { getIdentity, getPurchases, getReputationScore, getSavedListings, getStripeAccount } from "@/lib/queries";
import { requireSession } from "@/lib/session";
import { formatPrice } from "@/lib/types";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const { userId, email } = await requireSession("/dashboard");
  const identity = await getIdentity(userId);
  if (!identity) return <div className="mx-auto max-w-xl py-8"><div><p className="text-sm font-bold text-emerald-700">One quick step</p><h1 className="mt-1 text-3xl font-black text-slate-950">Set up your public profile</h1><p className="mt-2 text-slate-600">Choose a display name to start buying, selling, and connecting with creators.</p></div><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5"><IdentityForm mode="create" defaultName={email.split("@")[0] ?? ""} /></div></div>;

  const [score, purchases, saved, stripeAccount] = await Promise.all([getReputationScore(userId), getPurchases(userId), getSavedListings(userId), getStripeAccount(userId)]);
  const reputation = score?.score ?? identity.reputationScore;
  const paidPurchases = purchases.filter((purchase) => purchase.status === "paid");
  const setupItems = [
    { done: Boolean(identity.name && identity.bio), text: "Personalize your profile", href: "/profile" },
    { done: identity.verificationStatus === "verified", text: "Verify your identity", href: "/verification" },
    { done: Boolean(stripeAccount?.chargesEnabled), text: "Connect payouts for selling", href: "/stripe/onboarding" },
    { done: identity.isPro, text: "Explore Vennet Pro tools", href: "/pro" },
  ];

  return <main className="space-y-7 pb-12">
    <section className="relative overflow-hidden rounded-3xl bg-slate-950 px-7 py-9 text-white shadow-2xl shadow-slate-900/20 sm:px-10"><div className="absolute -right-12 -top-16 h-72 w-72 rounded-full bg-emerald-400/20 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Your Vennet space</p><h1 className="mt-2 text-4xl font-black tracking-tight">Good to see you, {identity.name}.</h1><p className="mt-3 max-w-xl text-base leading-7 text-slate-300">Keep your digital purchases close, find your next useful tool, or turn your own work into a storefront.</p></div><div className="flex flex-wrap gap-3"><Link href="/marketplace" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-white transition hover:bg-white/10">Explore marketplace</Link><Link href="/dashboard/seller" className="rounded-xl bg-emerald-300 px-4 py-3 text-sm font-black text-slate-950 transition hover:bg-emerald-200">Open seller studio</Link></div></div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Your library", paidPurchases.length, "Digital purchases ready when you need them", "/inventory"], ["Saved ideas", saved.length, "Offers you want to revisit", "/saved"], ["Reputation", reputation + "%", "Built through completed marketplace activity", "/reputation"], ["Plan", identity.isPro ? "Vennet Pro" : "Free", identity.isPro ? "Premium creator tools are active" : "Unlock more seller capacity and AI", "/pro"]].map(([label, value, caption, href], index) => <Link key={String(label)} href={String(href)} className={"rounded-3xl p-5 shadow-xl shadow-slate-900/5 transition hover:-translate-y-1 " + (index === 3 ? "bg-emerald-300 text-slate-950" : "border border-slate-200 bg-white")}><p className={"text-sm font-bold " + (index === 3 ? "text-slate-700" : "text-slate-600")}>{label}</p><p className="mt-3 text-3xl font-black tracking-tight">{value}</p><p className={"mt-2 text-sm leading-5 " + (index === 3 ? "text-slate-700" : "text-slate-500")}>{caption}</p><span className={"mt-4 inline-flex text-sm font-black " + (index === 3 ? "text-slate-800" : "text-emerald-800")}>Open →</span></Link>)}</section>

    <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-900/5"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Continue where you left off</p><h2 className="mt-1 text-2xl font-black text-slate-950">Your recent purchases</h2></div><Link href="/inventory" className="text-sm font-black text-emerald-800">View library →</Link></div>{purchases.length === 0 ? <div className="p-8"><p className="font-black text-slate-950">Your library is ready for its first digital purchase.</p><p className="mt-2 max-w-lg text-sm leading-6 text-slate-600">Every completed order keeps its delivery instructions, files, license details, and seller support in one place.</p><Link href="/marketplace" className="button-primary mt-5">Discover offers</Link></div> : <div className="divide-y divide-slate-100">{purchases.slice(0, 5).map((purchase) => <Link key={purchase.id} href="/inventory" className="flex items-center justify-between gap-4 px-6 py-4 transition hover:bg-slate-50"><div><p className="font-black text-slate-950">Marketplace order</p><p className="mt-1 text-sm text-slate-600">{purchase.createdAt.toLocaleDateString()} · {formatPrice(purchase.amountCents, purchase.currency)}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold capitalize text-emerald-700">{purchase.status}</span></Link>)}</div>}</div><aside className="rounded-3xl bg-slate-900 p-6 shadow-xl shadow-slate-900/15"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">A stronger Vennet account</p><h2 className="mt-1 text-2xl font-black text-white">Your next best steps</h2><div className="mt-5 space-y-3">{setupItems.map((item) => <Link key={item.text} href={item.href} className="flex items-center gap-3 rounded-2xl border border-white/10 p-3 text-sm transition hover:bg-white/[.06]"><span className={"grid h-6 w-6 shrink-0 place-items-center rounded-full font-black " + (item.done ? "bg-emerald-300 text-slate-950" : "border border-white/25 text-slate-300")}>{item.done ? "✓" : "→"}</span><span className={item.done ? "font-semibold text-slate-300 line-through" : "font-bold text-white"}>{item.text}</span></Link>)}</div></aside></section>

    <RecentlyViewedShelf />
    <section className="grid gap-4 md:grid-cols-3"><Link href="/collections" className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/5 transition hover:-translate-y-1"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Browse smarter</p><h2 className="mt-2 text-xl font-black text-slate-950">Explore collections</h2><p className="mt-2 text-sm leading-6 text-slate-600">Start with the kind of work you need: code, design, templates, education, and more.</p></Link><Link href="/saved" className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/5 transition hover:-translate-y-1"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Keep a shortlist</p><h2 className="mt-2 text-xl font-black text-slate-950">Saved offers</h2><p className="mt-2 text-sm leading-6 text-slate-600">Save products and services while you compare what fits your project best.</p></Link><Link href={identity.isPro ? "/ai" : "/pro"} className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6 shadow-lg shadow-emerald-900/5 transition hover:-translate-y-1"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">{identity.isPro ? "Pro tool" : "Upgrade option"}</p><h2 className="mt-2 text-xl font-black text-slate-950">{identity.isPro ? "Ask Vennet AI" : "Get more with Pro"}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{identity.isPro ? "Use your private weekly AI allowance to improve listings and plan your next release." : "Increase listing limits and unlock premium creator features."}</p></Link></section>
  </main>;
}
