import Link from "next/link";

const guides = [
  { number: "01", title: "Buy a digital item", summary: "Find an offer, review what you receive, and pay through Stripe.", steps: ["Open Explore and choose a category or use marketplace filters.", "Read the delivery, license, compatibility, and support details.", "Use Buy now or add compatible offers to your cart.", "After payment, open My library for files, access instructions, and seller support."] },
  { number: "02", title: "Set up your seller account", summary: "Connect Stripe before creating your first digital offer.", steps: ["Open Seller tools in the header.", "Choose Payout setup and complete Stripe onboarding.", "Return to Seller tools and select Create a listing.", "Add complete delivery and support information before publishing."] },
  { number: "03", title: "Create a great listing", summary: "Help buyers understand exactly what they are getting.", steps: ["Add a clear title, description, category, and price.", "Upload the digital file or provide accurate access instructions.", "Include license terms, compatibility, update policy, and support expectations.", "Add a preview image or demo, then publish when ready."] },
  { number: "04", title: "Find a past purchase", summary: "Everything you own lives in one organized library.", steps: ["Choose My library from the top navigation.", "Open the purchase you need.", "Download the file or follow the access instructions.", "Use the purchase support area if you need help from the seller."] },
];

export default function HelpPage() {
  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-7 py-10 text-white shadow-xl shadow-slate-950/15 sm:px-10"><div className="absolute -right-14 -top-16 h-60 w-60 rounded-full bg-emerald-400/25 blur-3xl" /><div className="relative max-w-2xl"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-300">Vennet Help</p><h1 className="mt-3 text-4xl font-black tracking-tight">Simple guides for buying and selling digital work.</h1><p className="mt-4 text-lg leading-8 text-slate-300">Quick, practical instructions for the most important parts of your Vennet account.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/marketplace" className="button-primary px-4 py-2.5 text-sm">Explore marketplace</Link><Link href="/dashboard/seller" className="rounded-xl border border-white/20 px-4 py-2.5 text-sm font-black text-white transition hover:bg-white/10">Open seller hub</Link></div></div></section>
    <section><div className="mb-5"><p className="text-sm font-black uppercase tracking-[.16em] text-emerald-700">Tutorials</p><h2 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Start here</h2></div><div className="grid gap-5 lg:grid-cols-2">{guides.map((guide) => <article key={guide.number} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/[0.04]"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-100 text-sm font-black text-emerald-800">{guide.number}</span><div><h3 className="text-xl font-black text-slate-950">{guide.title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{guide.summary}</p></div></div><ol className="mt-5 space-y-3">{guide.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-slate-700"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-black text-slate-600">{index + 1}</span><span>{step}</span></li>)}</ol></article>)}</div></section>
    <section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-7"><h2 className="text-xl font-black text-emerald-950">Need a quick answer?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-emerald-900">Use the page finder at the top to jump to any area of Vennet. For order-specific questions, open the purchase from My library and contact the seller through its support area.</p></section>
  </div>;
}
